import type {
  ActivityItem,
  AdminUser,
  AuditLogEntry,
  Brief,
  Doctor,
  FollowUp,
  MatchCandidate,
  Notification,
  OutreachContext,
} from "./types";

export const recruiters = [
  "Sarah Chen",
  "James Wilson",
  "Emma Thompson",
  "Michael O'Brien",
];

export const briefs: Brief[] = [
  {
    id: "brief-1",
    title: "Emergency Medicine Registrar - Royal Melbourne",
    client: "Royal Melbourne Hospital",
    location: "Melbourne, VIC",
    specialty: "Emergency Medicine",
    status: "open",
    assignedRecruiter: "Sarah Chen",
    openPositions: 2,
    createdDate: "2026-06-15",
    aiMatchConfidence: 87,
    ahpraStatus: "verified",
    notes: "Urgent fill required for winter surge.",
    roleType: "Registrar",
    startDate: "2026-08-01",
    employmentType: "Locum",
  },
  {
    id: "brief-2",
    title: "General Practitioner - Rural NSW",
    client: "NSW Health",
    location: "Dubbo, NSW",
    specialty: "General Practice",
    status: "in_progress",
    assignedRecruiter: "James Wilson",
    openPositions: 1,
    createdDate: "2026-05-20",
    aiMatchConfidence: 72,
    ahpraStatus: "pending",
    roleType: "GP",
    startDate: "2026-09-01",
    employmentType: "Permanent",
  },
  {
    id: "brief-3",
    title: "Cardiologist - Private Practice Sydney",
    client: "Sydney Heart Centre",
    location: "Sydney, NSW",
    specialty: "Cardiology",
    status: "open",
    assignedRecruiter: "Emma Thompson",
    openPositions: 1,
    createdDate: "2026-07-01",
    aiMatchConfidence: 91,
    ahpraStatus: "verified",
    roleType: "Consultant",
    startDate: "2026-10-01",
    employmentType: "Permanent",
    endDate: "2027-03-31",
    description: "Private cardiology practice seeking experienced consultant.",
    requirements: "FRACP, 10+ years post-fellowship experience.",
  },
];

export const doctors: Doctor[] = [
  {
    id: "doc-1",
    firstName: "Amelia",
    lastName: "Hartley",
    specialty: "Emergency Medicine",
    location: "Melbourne, VIC",
    ahpraStatus: "verified",
    ahpraNumber: "MED1234567",
    employmentType: "Locum",
    availability: "Available Aug 2026",
    email: "amelia.hartley@email.com",
    phone: "+61 412 345 678",
    status: "active",
    yearsExperience: 8,
    currentRole: "Emergency Registrar",
    currentEmployer: "Alfred Health",
    verificationSource: "API",
    verificationDate: "2026-06-10",
    ahpraLastChecked: "2026-07-10",
    subspecialties: ["Trauma", "Resuscitation"],
    education: ["MBBS University of Melbourne", "FRACP Emergency Medicine"],
    verificationNotes: "Verified via AHPRA API with no conditions.",
    supportingDocuments: [
      { name: "AHPRA_Certificate.pdf", type: "Verification", uploadedAt: "2026-06-10" },
    ],
    manualNotes: "Strong communicator, prefers metro locum roles.",
    aiNotesText: "8 years EM experience at tertiary hospitals. Available for winter surge locums.",
    cvFileName: "Hartley_CV_2026.pdf",
    cvParsingStatus: "parsed",
    parsedCvFields: [
      { field: "Specialty", value: "Emergency Medicine", confidence: 98, aiExtracted: true },
      { field: "AHPRA Number", value: "MED1234567", confidence: 95, aiExtracted: true },
    ],
    profileMeta: {
      createdBy: "Sarah Chen",
      createdAt: "2026-05-01",
      lastUpdated: "2026-07-10",
    },
    communicationLog: [
      {
        id: "cl-1",
        channel: "email",
        subject: "EM Role Introduction",
        timestamp: "2026-07-10T09:00:00Z",
        direction: "outbound",
      },
      {
        id: "cl-2",
        channel: "email",
        subject: "Re: Royal Melbourne opportunity",
        timestamp: "2026-07-11T14:30:00Z",
        direction: "inbound",
      },
    ],
  },
  {
    id: "doc-2",
    firstName: "David",
    lastName: "Nguyen",
    specialty: "General Practice",
    location: "Dubbo, NSW",
    ahpraStatus: "manual_review",
    ahpraNumber: "MED7654321",
    employmentType: "Permanent",
    availability: "Available Sep 2026",
    email: "david.nguyen@email.com",
    phone: "+61 423 456 789",
    status: "shortlisted",
    yearsExperience: 12,
    duplicate: false,
    aiGeneratedNotes: true,
    subspecialties: ["Rural Health", "Chronic Disease"],
    education: ["MBBS UNSW", "FRACGP"],
    manualNotes: "Willing to relocate to rural NSW.",
    aiNotesText: "Strong rural GP experience, 12 years in regional practice.",
    cvFileName: "Nguyen_CV_2026.pdf",
    cvParsingStatus: "parsed",
    ahpraLastChecked: "2026-07-05",
    profileMeta: {
      createdBy: "James Wilson",
      createdAt: "2026-04-15",
      lastUpdated: "2026-07-05",
    },
    communicationLog: [
      {
        id: "cl-3",
        channel: "sms",
        subject: "GP role follow-up",
        timestamp: "2026-07-08T11:00:00Z",
        direction: "outbound",
      },
    ],
  },
  {
    id: "doc-3",
    firstName: "Priya",
    lastName: "Sharma",
    specialty: "Cardiology",
    location: "Sydney, NSW",
    ahpraStatus: "verified",
    ahpraNumber: "MED9876543",
    employmentType: "Permanent",
    availability: "Immediate",
    email: "priya.sharma@email.com",
    phone: "+61 434 567 890",
    status: "active",
    yearsExperience: 15,
    verificationSource: "API",
    verificationDate: "2026-07-05",
    subspecialties: ["Interventional Cardiology"],
    education: ["MBBS University of Sydney", "FRACP Cardiology"],
    ahpraLastChecked: "2026-07-05",
    cvFileName: "Sharma_CV_2026.pdf",
    cvParsingStatus: "parsed",
    profileMeta: {
      createdBy: "Emma Thompson",
      createdAt: "2026-03-20",
      lastUpdated: "2026-07-05",
    },
  },
];

export const followUps: FollowUp[] = [
  {
    id: "fu-1",
    dueDate: "2026-07-15",
    priority: "high",
    status: "overdue",
    notes: "Follow up on AHPRA verification for Dr. Nguyen",
    assignee: "Sarah Chen",
    relatedCandidate: "David Nguyen",
    relatedBrief: "General Practitioner - Rural NSW",
  },
  {
    id: "fu-2",
    dueDate: "2026-07-20",
    priority: "medium",
    status: "pending",
    notes: "Send outreach to Dr. Hartley for EM role",
    assignee: "James Wilson",
    relatedCandidate: "Amelia Hartley",
    relatedBrief: "Emergency Medicine Registrar",
  },
  {
    id: "fu-3",
    dueDate: "2026-07-25",
    priority: "low",
    status: "in_progress",
    notes: "Schedule interview with Dr. Sharma",
    assignee: "Emma Thompson",
    relatedCandidate: "Priya Sharma",
  },
];

export const notifications: Notification[] = [
  {
    id: "n-1",
    type: "task",
    content: "Follow-up overdue: AHPRA verification for Dr. Nguyen",
    timestamp: "2026-07-13T08:00:00Z",
    read: false,
    relatedUrl: "/follow-ups/fu-1/edit",
  },
  {
    id: "n-2",
    type: "brief",
    content: "New AI matches found for Emergency Medicine Registrar brief",
    timestamp: "2026-07-12T14:30:00Z",
    read: false,
    relatedUrl: "/briefs/brief-1",
  },
  {
    id: "n-3",
    type: "verification",
    content: "AHPRA API verification completed for Dr. Sharma",
    timestamp: "2026-07-11T10:15:00Z",
    read: true,
    relatedUrl: "/doctors/doc-3",
  },
  {
    id: "n-4",
    type: "outreach",
    content: "Outreach draft saved for Dr. Hartley",
    timestamp: "2026-07-10T16:00:00Z",
    read: true,
    relatedUrl: "/outreach",
  },
  {
    id: "n-5",
    type: "system",
    content: "Weekly placement report is ready to view",
    timestamp: "2026-07-09T08:00:00Z",
    read: false,
    relatedUrl: "/reporting",
  },
];

export const activities: ActivityItem[] = [
  {
    id: "a-1",
    type: "verification",
    timestamp: "2026-07-11T10:15:00Z",
    description: "AHPRA verification completed via API",
    performedBy: "System",
    linkedCandidate: "Priya Sharma",
    ahpraBadge: "Verified",
  },
  {
    id: "a-2",
    type: "outreach",
    timestamp: "2026-07-10T09:00:00Z",
    description: "Outreach email sent to candidate",
    performedBy: "Sarah Chen",
    linkedCandidate: "Amelia Hartley",
    linkedCommunication: "EM Role Introduction",
  },
  {
    id: "a-3",
    type: "note",
    timestamp: "2026-07-09T16:45:00Z",
    description: "AI-generated screening note added",
    performedBy: "System",
    linkedCandidate: "David Nguyen",
    noteContent: "Strong rural GP experience, willing to relocate.",
    aiGenerated: true,
  },
  {
    id: "a-4",
    type: "status_change",
    timestamp: "2026-07-08T11:30:00Z",
    description: "Brief status changed to in progress",
    performedBy: "James Wilson",
    linkedCandidate: "David Nguyen",
    statusChange: "open → in_progress",
    hasAttachment: true,
  },
];

export const matchCandidates: MatchCandidate[] = [
  {
    id: "doc-1",
    name: "Dr. Amelia Hartley",
    specialty: "Emergency Medicine",
    location: "Melbourne, VIC",
    ahpraStatus: "Verified",
    confidence: 92,
    rationale: "Specialty match, location proximity, 8 years EM experience",
    availability: "Aug 2026",
    yearsExperience: 8,
    candidateStatus: "shortlisted",
    briefId: "brief-1",
    email: "amelia.hartley@email.com",
    phone: "+61 412 345 678",
  },
  {
    id: "doc-2",
    name: "Dr. David Nguyen",
    specialty: "General Practice",
    location: "Dubbo, NSW",
    ahpraStatus: "Manual Review",
    confidence: 78,
    rationale: "Rural GP experience, location match, availability aligned",
    availability: "Sep 2026",
    yearsExperience: 12,
    candidateStatus: "active",
    briefId: "brief-2",
    email: "david.nguyen@email.com",
    phone: "+61 423 456 789",
  },
];

export const adminUsers: AdminUser[] = [
  {
    id: "u-1",
    name: "Sarah Chen",
    email: "sarah.chen@recruitmed.com.au",
    role: "recruiter",
    status: "active",
    lastLogin: "2026-07-13T07:30:00Z",
    inviteSent: false,
    mfaEnabled: true,
  },
  {
    id: "u-2",
    name: "Admin User",
    email: "admin@recruitmed.com.au",
    role: "admin",
    status: "active",
    lastLogin: "2026-07-12T16:00:00Z",
    inviteSent: false,
    mfaEnabled: true,
  },
  {
    id: "u-3",
    name: "Report Viewer",
    email: "reports@recruitmed.com.au",
    role: "reporting",
    status: "active",
    lastLogin: "2026-07-10T09:00:00Z",
    inviteSent: true,
    mfaEnabled: false,
  },
];

export const auditLogs: AuditLogEntry[] = [
  {
    id: "al-1",
    timestamp: "2026-07-13T08:00:00Z",
    user: "Sarah Chen",
    action: "Export",
    objectType: "Report",
    objectName: "Dashboard CSV",
    details: "Exported dashboard summary",
    ipAddress: "203.45.67.89",
  },
  {
    id: "al-2",
    timestamp: "2026-07-12T14:30:00Z",
    user: "James Wilson",
    action: "Update",
    objectType: "Brief",
    objectName: "General Practitioner - Rural NSW",
    details: "Updated brief status to in_progress",
    ipAddress: "203.45.67.90",
  },
  {
    id: "al-3",
    timestamp: "2026-07-11T10:15:00Z",
    user: "System",
    action: "Verify",
    objectType: "Doctor",
    objectName: "Priya Sharma",
    details: "AHPRA API verification successful",
    ipAddress: "10.0.0.1",
  },
];

export const messageTemplates = [
  { id: "t-1", name: "Role Introduction", preview: "Dear {{name}}, we have an exciting opportunity..." },
  { id: "t-2", name: "Follow-up Reminder", preview: "Hi {{name}}, following up on our previous conversation..." },
  { id: "t-3", name: "Interview Invitation", preview: "Dear {{name}}, we would like to invite you for an interview..." },
];

export const retentionRules = [
  {
    id: "r-1",
    name: "Candidate Records",
    dataType: "Candidate Profile",
    retentionPeriod: "7 years",
    autoDelete: true,
    nextDeletion: "2026-08-01",
    lastRun: "2026-07-01",
    pendingCount: 12,
  },
  {
    id: "r-2",
    name: "Communication Logs",
    dataType: "Outreach",
    retentionPeriod: "3 years",
    autoDelete: true,
    nextDeletion: "2026-09-01",
    lastRun: "2026-06-15",
    pendingCount: 45,
  },
];

export const outreachContext: OutreachContext = {
  briefId: "brief-1",
  briefTitle: "Emergency Medicine Registrar - Royal Melbourne",
  client: "Royal Melbourne Hospital",
  candidateName: "Dr. Amelia Hartley",
  candidateSpecialty: "Emergency Medicine",
  consentStatus: "granted",
  previousContacts: [
    {
      id: "cl-1",
      channel: "email",
      subject: "EM Role Introduction",
      timestamp: "2026-07-10T09:00:00Z",
      direction: "outbound",
    },
    {
      id: "cl-2",
      channel: "email",
      subject: "Re: Royal Melbourne opportunity",
      timestamp: "2026-07-11T14:30:00Z",
      direction: "inbound",
    },
  ],
};
